### ISSUE TITLE
calibration crawlers failing due to connection error

### ISSUE THREAD

**Issue by niarenaw** [mkarim2017/standard_product#21]
**Describe the bug**
The `job-s1_calibration_crawler:develop` jobs are failing with the following error:
```
HTTPConnectionPool(host='aux.sentinel1.eo.esa.int', port=80): Max retries exceeded with url: /AUX_CAL/2021/12/01/ (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -2] Name or service not known'))
```

**To Reproduce**
Query for `job_type:"job-s1_calibration_crawler:develop"` in Figaro

**Comment by niarenaw** [comment]
Looks like host is hardcoded into pge: https://github.com/aria-jpl/s1_qc_ingest/blob/b15dc6db515647c36c11d1172d048c1c4929f6e7/crawl_cals.py#L42-L43

**Comment by al-niessner** [comment]
What is the new site? Without that, there is nothing to be done.

**Comment by niarenaw** [comment]
It looks like the old, commented out links are actually up again -- may just be a matter of switching them back.

https://github.com/aria-jpl/s1_qc_ingest/blob/b15dc6db515647c36c11d1172d048c1c4929f6e7/crawl_cals.py#L40-L41

**Comment by niarenaw** [comment]
Updated `QC_SERVER = 'https://qc.sentinel1.groupcls.com/'` and built new PGE. Confirmed it is working again.
