### ISSUE TITLE
401 error on scihub ipf scrapers

### ISSUE THREAD

**Issue by niarenaw** [mkarim2017/standard_product#22]
**Describe the bug**
The `job-ipf-scraper-scihub:develop` jobs are failing with the following error:
```
Failed to get IPF for acquisition-S1A_IW_SLC__1SDV_20211201T092528_20211201T092555_040813_04D858_CAA5-esa_scihub. 
Got code 401. 
 Traceback (most recent call last):
  File "/home/ops/verdi/ops/scihub_acquisition_scraper/ipf_scrape/ipf_version.py", line 215, in 
    ipf = extract_scihub_ipf(met)
  File "/home/ops/verdi/ops/scihub_acquisition_scraper/ipf_scrape/ipf_version.py", line 178, in extract_scihub_ipf
    raise Exception("Got code {}".format(prod_avail))
Exception: Got code 401
```

**To Reproduce**
Query for `job_type:"job-ipf-scraper-scihub:develop"` in Figaro

**Comment by niarenaw** [comment]
Looks like error stems from these lines: https://github.com/aria-jpl/scihub_acquisition_scraper/blob/develop/ipf_scrape/ipf_version.py#L157-L158 -- more investigation needed.

**Comment by al-niessner** [comment]
What changed that it suddenly quit working?

**Comment by niarenaw** [comment]
Just ran the pge manually and it finished without any problems. It looks like the runtime has increased (still investigating why this might be the case), but I believe raising the soft time limit in the pge/docker specs should temporarily resolve it.

**Comment by niarenaw** [comment]
The settings.auth call is not getting the correct user and password parameters passed in the `extract_scihub_ipf` function. They are both initialized to None and I am unsure how the correct values were initially passed. One option is to read the params from `/export/home/hysdsops/verdi/etc/settings.yaml`.

**Comment by niarenaw** [comment]
added credentials to `~/.netrc` and pge runs nominally now.
